<h1>Categorias</h1>

<div class="jumbotron">

    <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', ['route' => 'categorias/page']) ;?>

    <a href="<?= $this->url('home-admin',['controller'=>'categories','action'=>'new']); ?>" title="Nova Categoria" class="btn alert-success">Nova Categoria</a>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
        <?php foreach ($this->data as $entity) : ?>
            <tr>
                <td><?= $entity->getId(); ?></td>
                <td><?= $entity->getName(); ?></td>
                <td>
                    <a href="<?= $this->url('home-admin-intern', [
                        'controller' => 'categories',
                        'action' => 'edit',
                        'id' => $entity->getId()
                    ]) ;?>
                    " title="Edição de Categorias" class="btn alert-info">Editar</a>
                </td>
            </tr>
        <?php endforeach; ?>


    </table>

    <div class="">
    <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', ['route' => 'home-admin']) ;?>
    </div>
</div>
