<div class="jumbotron">
    <h1>Categorias</h1>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
        <?php foreach ($this->data as $entity) : ?>
            <tr>
                <td><?= $entity->getId(); ?></td>
                <td><?= $entity->getId(); ?></td>
                <td></td>
            </tr>
        <?php endforeach; ?>


    </table>


</div>
