<h1>Nova Categorias</h1>

<a href="<?= $this->url('home-admin',['controller'=>'categories','action'=>'index']); ?>" title="Categorias" class="btn btn alert-warning">Voltar | Categorias</a>

    <?php
    $form = $this->form;
    $form->setAttribute('Action', $this->url('home-admin', ['controller' => 'categories', 'action' => 'new']));
    $form->prepare();
    ?>
    <?= $this->form()->openTag($form);?>
    <?= $this->formHidden($form->get('id'));?>
    <div class="form-group">
        <div class="col-sm-10">
            <?=  $this->formRow($form->get('name'));?>
        </div>
    </div>

    <?=  $this->formSubmit($form->get('submit'));?>

    <?php $this->form()->closeTag();?>
