User\Entity\User:
    type: entity
    table: user_users
    repositoryClass: User\Entity\UserRepository
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: true
        activationKey:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: activation_key
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks:
    prePersist: [ setUpdatedAt ]
