<h1>Editar Categoria</h1>

    <a href="<?= $this->url('home-admin',['controller'=>'users','action'=>'index']); ?>" title="Usuário" class="btn btn alert-warning">Voltar | Usuários</a>

<div class="row">
    <div class="col-lg-6">
    <?php
    $form = $this->form;
    $form->setAttribute('Action', $this->url('home-admin-intern', ['controller' => 'users', 'action' => 'edit']));
    $form->prepare();
    ?>
    <?= $this->form()->openTag($form);?>
    <?= $this->formHidden($form->get('id'));?>
    <div class="form-group">
        <div class="col-sm-10">
            <?=  $this->formRow($form->get('name'));?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-10">
            <?=  $this->formRow($form->get('email'));?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-10">
            <?=  $this->formRow($form->get('password'));?>
        </div>
    </div>


    <?=  $this->formSubmit($form->get('submit'));?>

    <?php $this->form()->closeTag();?>
    </div>
</div>