<h1>Usuários</h1>

    <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', ['route' => 'home-admin']) ;?>


    <a href="<?= $this->url('home-admin',['controller'=>'users','action'=>'new']); ?>" title="Nova Usuário" class="btn alert-success">Novo Usuário</a>
    <br>
    <br>
    <table class="table table-condensed">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Ação</th>
        </tr>
        <?php foreach ($this->data as $entity) : ?>
            <tr>
                <td><?= $entity->getId(); ?></td>
                <td><?= $entity->getName(); ?></td>
                <td><?= $entity->getEmail(); ?></td>
                <td>
                    <a href="<?= $this->url('home-admin-intern', ['controller' => 'users','action' => 'edit','id' => $entity->getId()]) ;?>" title="Edição de Usuário" class="btn alert-info">Editar</a>

                    <a href="<?= $this->url('home-admin-intern', [
                        'controller' => 'users',
                        'action' => 'delete',
                        'id' => $entity->getId()
                    ]) ;?>" title="Deletar usuário" class="btn alert-danger">Deletar</a>
                </td>

            </tr>
        <?php endforeach; ?>


    </table>

    <div class="">
    <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', ['route' => 'bookstore-admin']) ;?>
    </div>

