<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . (int) $page;
    else
        return preg_replace('@/page/(\d+)@', '/page/' . (int) $page, $urlPattern);
};
?>

<?php if ($this->pageCount > 1): ?>


    <div class="center-block">
        <p>
            pagina
            <?php echo $this->current;?>
            de
            <?php echo $this->pageCount;?>
        </p>
        <ul class="pagination pagination-sm ">
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->previous) ?>"
                       title="Ir para pagina anterior"><span aria-hidden="true">&laquo;</span></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#" onclick="return false;"><span aria-hidden="true">&laquo;</span></a>
                </li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>

                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?> </a>
                    </li>
                <?php else: ?>
                    <li class="active"><a href="#"><?php echo $page; ?> </a></li>
                <?php endif; ?>

            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>"><span aria-hidden="true">&raquo;</span></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#" onclick="return false;"
                                        title="Ir para próxima pagina"><span aria-hidden="true">&raquo;</span></a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>