<h1>Usuários</h1>

<?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator') ;?>


<a href="<?= $this->url('user-admin/default',['action'=>'new']); ?>" title="Nova Usuário" class="btn alert-success">Novo</a>
<br>
<br>
<table class="table table-condensed">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Ação</th>
    </tr>
    <?php foreach ($this->data as $entity) : ?>
        <tr>
            <td><?= $entity->getId(); ?></td>
            <td><?= $entity->getName(); ?></td>
            <td><?= $entity->getEmail(); ?></td>
            <td>
                <a href="<?= $this->url('user-admin/default',['controller' => 'users','action'=>'edit', 'id' => $entity->getId()]); ?>" title="Edição de Usuário" class="btn alert-info">Editar</a>
                <a href="<?= $this->url('user-admin/default',['controller' => 'users','action'=>'delete', 'id' => $entity->getId()]); ?>" title="delete de Usuário" class="btn alert-danger">Delete</a>
            </td>

        </tr>
    <?php endforeach; ?>


</table>

<div class="">
    <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator') ;?>
</div>

