<h1>Novo Usuário</h1>

<a href="<?= $this->url('user-admin/default',['controller'=>'users','action'=>'index']); ?>" title="Usuário" class="btn btn alert-warning">Voltar | Usuários</a>

<div class="row">
    <div class="col-lg-6">
        <?php
        $form = $this->form;
        $form->setAttribute('Action', $this->url('user-admin/default', ['controller' => 'users', 'action' => 'new']));
        $form->prepare();
        ?>
        <?= $this->form()->openTag($form);?>
        <?= $this->formHidden($form->get('id'));?>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('name'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('email'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('password'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('confirmation'));?>
            </div>
        </div>

        <?=  $this->formSubmit($form->get('submit'));?>

        <?php $this->form()->closeTag();?>

    </div>
</div>