<h1>Novo Livro</h1>

<a href="<?= $this->url('home-admin',['controller'=>'books','action'=>'index']); ?>" title="Livros" class="btn btn alert-warning">Voltar | Livros</a>
<div class="row">
    <div class="col-lg-6">
        <?php
        $form = $this->form;
        $form->setAttribute('Action', $this->url('home-admin', ['controller' => 'books', 'action' => 'new']));
        $form->prepare();
        ?>
        <?= $this->form()->openTag($form);?>
        <?= $this->formHidden($form->get('id'));?>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('categories'));?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('name'));?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('author'));?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('price'));?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('isbn'));?>
            </div>
        </div>

        <?=  $this->formSubmit($form->get('submit'));?>

        <?php $this->form()->closeTag();?>
    </div>
</div>