<h1>Login</h1>
<div class="row">
    <div class="col-lg-3">
<?php if ($this->error) : ;?>
    <div class="alert alert-danger" role="alert">Usuário ou Senha Inválidos</div>
<?php endif; ;?>

    <?php
    $form = $this->form;
    $form->setAttribute('Action', $this->url('user-auth'));
    $form->prepare();
    ?>
    <?= $this->form()->openTag($form);?>
    <div class="form-group">
        <div class="col-sm-12">
            <?=  $this->formRow($form->get('email'));?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            <?=  $this->formRow($form->get('password'));?>
        </div>
    </div>

    <?=  $this->formSubmit($form->get('submit'));?>

    <?php $this->form()->closeTag();?>
    </div>
</div>