<h1>Registro</h1>


<div class="row">
    <div class="col-lg-6">
        <?php
        if ($this->success)
            echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';
        if ($this->error)
            echo '<div class="alert alert-danger">'.$this->error[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';
        ?>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('user-register', ['controller' => 'index', 'action' => 'register']));
        $form->prepare();
        ?>
        <?= $this->form()->openTag($form);?>
        <?= $this->formHidden($form->get('id'));?>
        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('name'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('email'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('password'));?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <?=  $this->formRow($form->get('confirmation'));?>
            </div>
        </div>

        <?=  $this->formSubmit($form->get('submit'));?>

        <?php $this->form()->closeTag();?>

    </div>
</div>