<div class="jumbotron">
    <h3><?= $this->translate('Home');?></h3>
    <p><?= $this->translate('Hello');?> Amigo <?= $this->translate('Welcome');?>!!!</p>
</div>
<div class="jumbotron">
    <p>
        <?php
//        $this->dateFormat(-->
//            new DateTime(),-->
//            IntlDateFormatter::LONG,-->
//            IntlDateFormatter::MEDIUM,-->
//            'pt_BR'-->
//        );-->

//        $this->plugin('dateFormat')->setTimezone('America/Sao_Paulo')->setLocale('pt_BR');
//        echo $this->dateFormat(new DateTime(), IntlDateFormatter::MEDIUM);

        echo $this->numberFormat(
            1234.56789,
            NumberFormatter::DECIMAL,
            NumberFormatter::TYPE_DEFAULT
        )."<br>";

        echo $this->numberFormat(
            1234.56789,
            NumberFormatter::PERCENT,
            NumberFormatter::TYPE_DEFAULT
            )."<br>";

        echo $this->numberFormat(
            0.12654984515454,
            NumberFormatter::SCIENTIFIC,
            NumberFormatter::TYPE_DEFAULT
        )."<br>";

        echo $this->currencyFormat(
                7.77,
                'BRL'
            )."<br>";

        echo $this->translatePlural('Animal', 'Animais', 2);

        ?>
    </p>
</div>

